export const QIITA_USER_TOKENS = [
  process.env.NEXT_PUBLIC_QIITA_TOKEN_MELLBROTHER,
  process.env.NEXT_PUBLIC_QIITA_TOKEN_TOM_TAKERU,
  process.env.NEXT_PUBLIC_QIITA_TOKEN_ATOK,
  process.env.NEXT_PUBLIC_QIITA_TOKEN_KAZUKIIII,
];
